services:
  - type: web
    name: SmartAgriVision
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.10.13
